language: dart
dart:
  - stable
  - dev

# Trusty is necessary to install Chrome.
dist: trusty
sudo: true

# Install Chrome
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  # Install Content Shell
  - wget https://storage.googleapis.com/dart-archive/channels/stable/release/latest/content_shell/content_shell-linux-x64-release.zip
  - unzip content_shell-linux-x64-release.zip
  - rm content_shell-linux-x64-release.zip
  - export PATH="${PWD%/}/$(echo drt-*-full-stable-*):$PATH"

  # Install Dartium
  - wget https://storage.googleapis.com/dart-archive/channels/stable/release/latest/dartium/dartium-linux-x64-release.zip
  - unzip dartium-linux-x64-release.zip
  - rm dartium-linux-x64-release.zip
  - mv `echo dartium-*-full-stable-*`/{chrome,dartium}
  - export PATH="${PWD%/}/$(echo dartium-*-full-stable-*):$PATH"
