language: dart
dart:
  - stable
  - dev
with_content_shell: true

# Trusty is necessary to install Chrome.
dist: trusty
sudo: true

# Install Chrome
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  # Install Dartium
  - wget https://storage.googleapis.com/dart-archive/channels/stable/release/latest/dartium/dartium-linux-x64-release.zip
  - unzip dartium-linux-x64-release.zip > /dev/null
  - rm dartium-linux-x64-release.zip
  - mv dartium-*-full-stable-*/{chrome,dartium}
  - export PATH="${PWD%/}/$(echo dartium-*-full-stable-*):$PATH"
