language: dart
dart:
  - stable
  - dev
with_content_shell: true

# Trusty is necessary to install Chrome.
dist: trusty
sudo: true

# Install Chrome
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - content_shell

  # Install Dartium
  - wget https://storage.googleapis.com/dart-archive/channels/stable/release/latest/dartium/dartium-linux-x64-release.zip
  - unzip dartium-linux-x64-release.zip
  - rm dartium-linux-x64-release.zip
  - mv `echo dartium-*-full-stable-*`/{chrome,dartium}
  - export PATH="${PWD%/}/$(echo dartium-*-full-stable-*):$PATH"
