name: unittest
version: 0.12.0-dev
author: Dart Team <misc@dartlang.org>
description: A library for writing dart unit tests.
homepage: https://github.com/dart-lang/unittest
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  stack_trace: '>=0.9.0 <2.0.0'

  # Because unittest exports matcher, it needs to keep its version constraint
  # tight to ensure that a constraint on unittest properly constraints all
  # features it provides.
  matcher: '>=0.11.4 <0.11.5'
dev_dependencies:
  fake_async: '>=0.1.2 <0.2.0'
  metatest:
    git:
      ref: b6348d7e7f3c5b00a48aa579694457d1abd36b69
      url: https://github.com/dart-lang/metatest
