name: unittest
version: 0.12.0-dev
author: Dart Team <misc@dartlang.org>
description: A library for writing dart unit tests.
homepage: https://github.com/dart-lang/unittest
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  args: '>=0.12.1 <0.13.0'
  stack_trace: '>=1.2.0 <2.0.0'

  # Using the pre-release version of matcher. When published we will go back
  # using a tight version constraint to ensure that a constraint on unittest
  # properly constraints all features it provides.
  matcher:
    git: https://github.com/dart-lang/matcher.git
dev_dependencies:
  fake_async: '>=0.1.2 <0.2.0'
